WikiDP/wikidp-portal

wikidp/portal_routes.py
wikidp/wikidata.py

- wikidata test function now returns fudged dictionary string; and
- home page now requests test text and displays.

FIX - Home page output

---

wikidp/portal_routes.py
wikidp/templates/home.html
wikidp/templates/temp.html
wikidp/wikidata.py

- Added sample landing page
- Included a form to enter Q#'s as a string
- Uses pywikibot to gather Aliases and P#'s for each item
- Returns list of information

FEAT - Group Searching on homepage

---

.gitignore
setup.py
wikidp/__init__.py
wikidp/config.py
wikidp/const.py
wikidp/portal_routes.py
wikidp/wikidata.py

- ordering of imports;
- variable name for app (my fault);
- variable names should be camel case, e.g. `q_id` not `qID`; and
- small spacing issues, e.g. before braces in `print ()` statements.

REVIEW - Style points

---

README.md
setup.py
wikidp/config.py
wikidp/portal_routes.py
wikidp/queries.py
wikidp/wikidata.py

- removed all pywikibot code;
- added basic wikidataintegrator example;
- credentials config through environment variables;
- replaced all routes with simple query proof of concept home page.
- hacked queries as string constants for now; and
- added basic README with quick start instructions.

FEAT - Wikidata Integrator

---

README.md

Is this a suitable way to communicate how to get to the app?

added note about browser address

---

README.md

DOC - Fixed README link

---

.gitignore
README.md
run.sh
setup.py
setup.sh
venv.sh
wikidp/config.py
wikidp/wikitools-setup.py

- ensured setup.py is up to date with only the necessary versioned dependencies;
- updated the README to match;
- added helper scripts for setup, installation and running; and
- added extra logging info.

FIX - Setup.py and README instructions

---

wikidp/templates/about.html
wikidp/templates/base.html
wikidp/templates/contribute.html
wikidp/templates/home.html
wikidp/templates/navbar.html
wikidp/templates/preview-item.html
wikidp/templates/search_results.html
wikidp/templates/welcome.html

- tidied use of includes in Jinja templates; and
- fixed about page structure.

FIX - Use of templates

---

wikidp/model.py

- added MIME property to `PuidSearchResult`;
- amended PUID query to return a MIME type as well;
- added search by MIME method to `PuidSearchResult`;
- `PuidSearchResult.__str__()` also prints MIME type; and
- tidied original format list query.
Begins to address #29

FEAT - MIME search methods

---

ansible/host_vars/vagrant
ansible/roles/wikidp.wikibase/defaults/main.yml
ansible/roles/wikidp.wikibase/files/nginx/etc/nginx/nginx.conf
ansible/roles/wikidp.wikibase/handlers/main.yml
ansible/roles/wikidp.wikibase/meta/main.yml
ansible/roles/wikidp.wikibase/tasks/main.yml
ansible/roles/wikidp.wikibase/tasks/nginx/configure.yml
ansible/roles/wikidp.wikibase/tasks/nginx/main.yml
ansible/roles/wikidp.wikibase/tasks/wikibase/dependencies.yml
ansible/roles/wikidp.wikibase/tasks/wikibase/main.yml
ansible/roles/wikidp.wikibase/tasks/wikibase/mediawiki.yml
ansible/roles/wikidp.wikibase/tasks/wikibase/php-fpm.yml
ansible/roles/wikidp.wikibase/tasks/wikibase/wikibase.yml
ansible/roles/wikidp.wikibase/templates/nginx/etc/nginx/sites-available/wikibase.conf.j2
ansible/roles/wikidp.wikibase/templates/php/etc/php/fpm/php-fpm.conf.j2
ansible/roles/wikidp.wikibase/templates/php/etc/php/fpm/php.ini.j2
ansible/roles/wikidp.wikibase/templates/php/etc/php/fpm/pool.d/pool.conf.j2
ansible/roles/wikidp.wikibase/tests/inventory
ansible/roles/wikidp.wikibase/tests/test.yml
ansible/roles/wikidp.wikibase/tests/vagrant.yml
ansible/roles/wikidp.wikibase/vars/main.yml
ansible/vagrant.yml

New ansible role for installation:
- and config of mediawiki & dependencies;
- of tools for automated mediawiki management; and
- and config of the WikiBase extension plus dependencies.

FEAT : Automated Wikibase Installation

---

wikidp/static/css/wikidp.css
wikidp/static/js/wikidp.js
wikidp/templates/base.html
wikidp/templates/login.html
wikidp/templates/navbar.html
wikidp/templates/page.html

FEAT: Added UI for login modal

---

.gitignore
wikidp/config.py
wikidp/static/css/wikidp.css
wikidp/templates/snippets/modal_login.html

FEAT: Adding more styling to login modal

---

DOCKER.md
Dockerfile
wikidp/__init__.py

- added 2 stage `Dockerfile` that produces lightweight alpine image; and
- added basic docker instructions in `DOCKER.md`.

FEAT - Docker build from local source

---

wikidp/controllers/search.py
wikidp/models.py
wikidp/templates/search_results.html
wikidp/utils.py

@emulatingkat and I worked on adding a Model to directly search by File Format extension similar to how we handle PUID
(Closes #83)
(Closes #80)

FEAT: Adding File Format Ext Search support

---

DOCKER.md
Dockerfile.dev
README.md
docker-dev.sh
requirements.txt

- added `Dockerfile.dev` to build development environment;
- `docker-dev.sh` and `requirements.txt`; and
- instructions on how to use the Docker image.

FEAT - Development Docker environment

---

.pre-commit-config.yaml
.travis.yml
wikidp/__init__.py
wikidp/controllers/api.py
wikidp/routes/__init__.py
wikidp/routes/_filters.py
wikidp/utils.py

- added Travis build and QA via `.travis.yml`:
- uses Python 3.6 environment;
- installs testing tools;
- performs automated QA using `pylint`, `pre-commit`, `pytest`, `pep-257`, and `twine`;
- various minor code clean-ups:
- removed unnecessary else clauses;
- shortened long lines;
- added some PyDoc here and there;
- fixed some empty checks;
- fixed log print formatting; and
- added `.pre-commit-config.yaml` for consistency QA on Travis;

FEAT - Automated code QA

---

wikidp/controllers/search.py
wikidp/models.py
wikidp/templates/search_results.html
wikidp/utils.py

- includes the fix to URL encoding; and
- improvements to Docker roll out.
See https://staging.wikidp.org to test site.

FIX: Text token search and URL encoding

---

wikidp/routes/pages.py
wikidp/static/js/wikidp.js
wikidp/templates/profile.html

- added skeleton user profile page wired into OAuth;
- removed redundant output strings for profile output; and
- wired user icon to profile page.

FEAT: Basic user profile page

---

wikidp/config.py
wikidp/const.py
wikidp/controllers/__init__.py
wikidp/controllers/api.py
wikidp/controllers/pages.py
wikidp/controllers/search.py
wikidp/models.py
wikidp/routes/_converters.py
wikidp/routes/_filters.py
wikidp/routes/api.py
wikidp/routes/forms.py
wikidp/routes/pages.py
wikidp/routes/search.py
wikidp/sparql.py
wikidp/utils/__init__.py
wikidp/utils/wd_int_utils.py

- Does what it says on the tin.

REFACT - War on DocLint

---

run.sh
setup.py
wikidp/models.py
wikidp/routes/_converters.py
wikidp/routes/pages.py
wikidp/static/js/wikidp.js
wikidp/templates/profile.html

Working OAuth integration with Wikidataintegrator.

FEAT: OAuth

---

wikidp/controllers/api.py
wikidp/controllers/pages.py
wikidp/static/css/wikidp.css
wikidp/templates/base.html
wikidp/templates/snippets/property_checklist.html

(#103) FEAT: Adding support for nesting qualifier props within checklist

---

DOCKER.md
wikidp/routes/oauth.py
wikidp/routes/pages.py

REFACT: Small improvements.

---

wikidp/controllers/api.py
wikidp/routes/api.py
wikidp/sparql.py
wikidp/static/js/item_contribute.js
wikidp/templates/item_contribute.html
wikidp/templates/snippets/contribute_input_templates.html
wikidp/utils/__init__.py

Once #111  is merged, this will be a follow-on PR to implement references
- closes #32

(#32) FEAT: Adding Support for Contributing References
